### ISSUE TITLE
With a gradle multiproject, SS may be illegally altering a zip and crashing on Linux

### ISSUE THREAD

**Issue by mezz** [md-5/SpecialSource#45] opened 2017-08-27 05:05 UTC
I have a gradle multproject, [Binnie's mods](https://github.com/ForestryMC/Binnie).
A Linux build server is set up to automatically build the combined mod jar.
The build crashes at "reobf" every time, and the gradle daemon quits with no error message. [Travis log](https://travis-ci.org/ForestryMC/Binnie/jobs/268782436).

This turned out to be caused by a [JDK crash](https://gist.github.com/mezz/acb36bed5953a044be44341b4a5d2603) which I reported and hope to hear back on.

@cpw was able to reproduce the issue on his Linux machine, and believes the JDK crash is caused by some part of the build process reading a zip file while another is editing it. 
This only crashes on Linux because Windows locks the file and Linux does not.

We suspect SpecialSource is involved, if not I still hope to get your thoughts on this.

**Comment by matthewprenger** [comment] 2017-08-27 05:40
Interesting that this popped up again. Sounds like the exact same problem I had years ago.

MinecraftForge/ForgeGradle#64 and MinecraftForge/ForgeGradle@71b0177266c865e604d3419e386f54b74ebec5bc

**Comment by mezz** [comment] 2017-08-27 06:04
Thanks, it really does look the same.
The code has been refactored since then, maybe it the bug is back?

**Comment by AbrarSyed** [comment] 2017-08-27 06:06
The internals of the reobfuscation task shouldn't have changed. As far as I know (well, since I'm out of the loop I could be wrong) the reobfuscation process has not significantly changed.

On August 27, 2017 1:04:25 AM CDT, mezz <notifications@github.com> wrote:
>Thanks, it really does look the same.
>The code has been refactored since then, maybe it the bug is back?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/md-5/SpecialSource/issues/45#issuecomment-325179129

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mezz** [comment] 2017-08-27 06:06
Here is the current code, it looks similar to the original fix.
https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.3/src/main/java/net/minecraftforge/gradle/user/TaskSingleReobf.java#L174

**Comment by mezz** [comment] 2017-08-27 06:17
I have a hard time seeing if the current code has an issue, it looks fine to me.

**Comment by mezz** [comment] 2017-08-27 06:49
Further investigation from Player, Tahg, and cpw show that Java 9 has fixed this long-standing JDK issue.
There are some issues building the project with Java 9 but I think they may be easier than solving this one.

**Comment by md-5** [comment] 2017-08-27 07:06
Java crashes are generally Java bugs. Unless something SS is doing is always triggering this Java bug, I don't think its really our issue

**Comment by nallar** [comment] 2017-09-01 14:19
Maybe this would be fixed by using `JarFile.close()` ([recently added](https://github.com/md-5/SpecialSource/pull/44/files)) where appropriate in ForgeGradle?

That PR was made because FG currently leaks file handles. However SpecialSource hasn't yet had a new release since that PR was merged so I hadn't made a PR for ForgeGradle to use `JarFile.close`.

A SIGSEGV crash under ZipFile.getEntry can be reproduced by doing a build in a gradle daemon, forcibly closing the zip file handles (eg with process explorer on windows), then doing another build in the same daemon.

**Comment by mezz** [comment] 2017-09-02 02:28
That sounds plausible. I'm pretty sure this is an FG issue and not SS directly.
@md-5 could you make a new SS release so we can implement this FG fix and see if it has an effect?

**Comment by md-5** [comment] 2017-09-02 07:14
I've release SS-1.8 and it will be in central soon. Note however that it also includes Java 9 support so that will almost certainly have other effects on FG.

**Closed** 2017-09-09 10:58 UTC
